CATALOGUE_HOST: catalogue.backend-{{ env }}.prudhvisai.space
USER_HOST: user.backend-{{ env }}.prudhvisai.space
CART_HOST: cart.backend-{{ env }}.prudhvisai.space
SHIPPING_HOST: shipping-{{ env }}.prudhvisai.space
PAYMENT_HOST: payment-{{ env }}.prudhvisai.space