[mongodb]
mongodb-dev.prudhvisai.space
[catalogue]
catalogue.prudhvisai.space 
[redis]
redis.prudhvisai.space 
[user]
user.prudhvisai.space 
[cart]
cart.prudhvisai.space 
[frontend]
frontend.prudhvisai.space 
[mysql]
mysql.prudhvisai.space 
[shipping]
shipping.prudhvisai.space  
[rabbitmq]
rabbitmq.prudhvisai.space 
[payment]
payment.prudhvisai.space 

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[localhost]
localhost